name: REFRESH OBIT.BAPC.KR

on:
  push:
    paths-ignore:
      - 'export/**'
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread
          pip install jinja2
          pip install uuid
          pip install feedparser
          pip install beautifulsoup4

      - name: Run Python script
        run: python page_builder.py # 이곳에 실제 파이썬 파일명을 적어주세요.
        env: 
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Commit & push
        run: |
          cd export
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Auto update pages $(date +'%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
          git push https://${{ secrets.GH_TOKEN }}@github.com/moah0o0/obit.bapc.kr.git HEAD:main

